version: '3.1'
services:
  db:
    build: ./postgres
    ports:
      - "5432:5432"
  time-tracking-backend:
    build: ./time-tracking-backend
    ports:
      - "8080:8080"
  google-login-poc-app:
    build: ./google-login-poc-app
    ports:
      - "80:80"
