version: '3.1'
services:
  db:
    build: ./postgres
  time-tracking-backend:
    build:
      context: ./time-tracking-backend
      args:
        - RUN_TESTS=true
    depends_on:
      - "db"
      - "elasticsearch"
      - "jira"
    ports:
      - "8081:8081"
  google-login-poc-app:
    build: ./google-login-poc-app
    ports:
      - "3000:3000"
  jira:
    build: ./jira
    ports:
      - "8080:8080"
  elasticsearch:
    build: ./elasticsearch
    environment:
      - cluster.name=time-tracking-cluster
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    build: ./logstash
    depends_on:
      - "elasticsearch"
      - "db"
  sonarqube:
    build: ./sonarqube
    ports:
      - "9000:9000"
